version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=True
      - SECRET_KEY=withme-super-secret-production-key-2026
      - JWT_SECRET_KEY=withme-jwt-ultra-secure-key-2026
      - DATABASE_URL=sqlite:///withme.db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
