"""Add performance indexes across models

Revision ID: 56b28c76ab34
Revises: 
Create Date: 2026-09-12 16:42:37.386919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b28c76ab34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_approx_latitude'), ['approx_latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_approx_longitude'), ['approx_longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_location_type'), ['location_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_status'), ['status'], unique=False)

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_participants_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_status'), ['status'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_category'), ['category'], unique=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_is_private'), ['is_private'], unique=False)

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interests_category'), ['category'], unique=False)

    with op.batch_alter_table('location_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_preferences_approx_latitude'), ['approx_latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_preferences_approx_longitude'), ['approx_longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_preferences_location_enabled'), ['location_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_preferences_show_on_nearby'), ['show_on_nearby'], unique=False)

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)

    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goals_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_interests_interest_id'), ['interest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_interests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_skills_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skills_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_skills_skill_id'))

    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_interests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_interests_interest_id'))

    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_goals_goal_id'))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_stage'))
        batch_op.drop_index(batch_op.f('ix_projects_category'))

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    with op.batch_alter_table('location_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_preferences_show_on_nearby'))
        batch_op.drop_index(batch_op.f('ix_location_preferences_location_enabled'))
        batch_op.drop_index(batch_op.f('ix_location_preferences_approx_longitude'))
        batch_op.drop_index(batch_op.f('ix_location_preferences_approx_latitude'))

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interests_category'))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_is_private'))
        batch_op.drop_index(batch_op.f('ix_groups_category'))

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_category'))

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_status'))

    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilities_user_id'))

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_participants_activity_id'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_status'))
        batch_op.drop_index(batch_op.f('ix_activities_location_type'))
        batch_op.drop_index(batch_op.f('ix_activities_event_date'))
        batch_op.drop_index(batch_op.f('ix_activities_category'))
        batch_op.drop_index(batch_op.f('ix_activities_approx_longitude'))
        batch_op.drop_index(batch_op.f('ix_activities_approx_latitude'))

    # ### end Alembic commands ###
